create table client
(
    id           integer generated by default as identity primary key,
    username     varchar(100) unique ,
    email        varchar(100),
    phone_number varchar(12) not null,
    role         varchar(100) check(role in('ADMIN', 'USER', 'AUTHUSER', 'AUTHOR')),
    password     varchar(100),
    image        varchar(500)
);

create table album
(
    id           integer generated by default as identity primary key,
    name         varchar(100),
    countofplays integer,
    rating       integer,
    countofmusic integer,
    status       varchar(100) check(status in('PUBLISH', 'PRIVATE')),
    image_uri    varchar(500)
);

create table music
(
    id           integer generated by default as identity primary key,
    name         varchar(100),
    rating       integer,
    countofplays integer,
    album_id     integer references album (id) on delete cascade,
    image_uri    varchar(500) unique,
    audio_uri    varchar(500) unique
);

create table author_album
(
    id        integer generated by default as identity primary key,
    album_id  integer references album (id) on delete cascade,
    author_id integer references client (id) on delete cascade
);

create table author_music
(
    id        integer generated by default as identity primary key,
    music_id  integer unique references music (id) on delete cascade,
    author_id integer unique references client (id) on delete cascade
);

select * from client;